# does not touch running state
- name: enable httpd service
  service:
      name: httpd
      enabled: yes

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
    enabled: yes

- name: restart httpd
  service:
      name: httpd
      state: restarted
      enabled: yes
